
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBERstatement : expressionexpression : expression '+' expression\n                  | expression '-' expression\n    expression : NUMBER"
    
_lr_action_items = {'NUMBER':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-1,-4,-2,-3,]),'+':([2,3,6,7,],[4,-4,4,4,]),'-':([2,3,6,7,],[5,-4,5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,],[2,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','lex_synth.py',26),
  ('expression -> expression + expression','expression',3,'p_expression_binop','lex_synth.py',30),
  ('expression -> expression - expression','expression',3,'p_expression_binop','lex_synth.py',31),
  ('expression -> NUMBER','expression',1,'p_expression_number','lex_synth.py',39),
]
